name: Paypay PHP SDK CI
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
      - uses: actions/checkout@v2

      - name: Run composer
        run: composer install

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make run_mock

      - name: Code Climate before-build
        env:
          CC_TEST_REPORTER_ID: fa3e49a5bc2592fd1397209f68833c40c47adb8de7940e460ffd07a852922660
        run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coverall_upload

      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)

      - name: Code Climate after-build
        env:
          CC_TEST_REPORTER_ID: fa3e49a5bc2592fd1397209f68833c40c47adb8de7940e460ffd07a852922660
        run: ./cc-test-reporter after-build --exit-code 0
