name: Paypay PHP SDK CI
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 148ea266f96a637c1f5f85179aab3ba533a5a64d0dfccab0ab7ce703f44fd80b
    strategy:
      matrix:
        php-version: [7.3]
    steps:
      - uses: actions/checkout@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run composer
        run: composer install

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make run_mock

      - name: Before script
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coverall_upload

      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
