name: Paypay PHP SDK CI
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
      - uses: actions/checkout@v2

      - name: Run composer
        run: composer install

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make run_mock

      - name: Upload coverage GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          # Consumed by the `build-ci-target.yml` `upload-codeclimate` job.
          name: clover-coverage-${{ matrix.php-version }}
          path: ./build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coverall_upload

      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
